version: '3.8'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/dev'
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    secrets:
      - db_user
      - db_password
      - db_name

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB_FILE: /run/secrets/db_name
    ports:
      - '5432:5432'
    secrets:
      - db_user
      - db_password
      - db_name

secrets:
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password
  db_name:
    file: ./secrets/db_name
